name: Actions Workflow

on: push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: create env file
        run: | 
          touch .env
          pwd
      - name: checkout actions
        uses: actions/checkout@v1
      - name: create env file
        run: |
          touch .env
          pwd
          ls
      - name: Simple javascript actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Yomi
      - name: Log creating time
        run: echo "${{steps.greet.outputs.time}}"

