name: Shell Commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello world"
      - name: echo multi-line script
        run: |
          node -v
          npm -v
          pwd
      - name: python command
        run: |
          import platform
          print (platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: output
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
